// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyKzbk9_q42cQ-9O7ttXlSqLKTaBvr9OQ',
    appId: '1:942515568123:web:177ccb34e4c7ea3f869f5e',
    messagingSenderId: '942515568123',
    projectId: 'glaze-manager',
    authDomain: 'glaze-manager.firebaseapp.com',
    storageBucket: 'glaze-manager.firebasestorage.app',
    measurementId: 'G-FLF0R81X83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9N5XW0IGEAkVeHdFpRqt3Hq689NhkRLE',
    appId: '1:942515568123:android:288e8f252f7ea017869f5e',
    messagingSenderId: '942515568123',
    projectId: 'glaze-manager',
    storageBucket: 'glaze-manager.firebasestorage.app',
    androidClientId: '942515568123-g7d6nih90qkc70t17i8qaqka6dcmr6ah.apps.googleusercontent.com'
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuV2aYzA0xh-fl0LtikHBLcH1HgknqBC8',
    appId: '1:942515568123:ios:3b7e1d736852f9c2869f5e',
    messagingSenderId: '942515568123',
    projectId: 'glaze-manager',
    storageBucket: 'glaze-manager.firebasestorage.app',
    iosClientId: '942515568123-b3cstk3rf9tlvg4bvtu7bn10r51aq6eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.glazeManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuV2aYzA0xh-fl0LtikHBLcH1HgknqBC8',
    appId: '1:942515568123:ios:3b7e1d736852f9c2869f5e',
    messagingSenderId: '942515568123',
    projectId: 'glaze-manager',
    storageBucket: 'glaze-manager.firebasestorage.app',
    iosClientId: '942515568123-b3cstk3rf9tlvg4bvtu7bn10r51aq6eo.apps.googleusercontent.com',
    iosBundleId: 'com.example.glazeManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyKzbk9_q42cQ-9O7ttXlSqLKTaBvr9OQ',
    appId: '1:942515568123:web:8daea0a48ad42039869f5e',
    messagingSenderId: '942515568123',
    projectId: 'glaze-manager',
    authDomain: 'glaze-manager.firebaseapp.com',
    storageBucket: 'glaze-manager.firebasestorage.app',
    measurementId: 'G-DKGCBEKQHD',
  );

}