// Mocks generated by Mockito 5.4.6 from annotations
// in glaze_manager/test/screens/main_tab_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i11;
import 'dart:typed_data' as _i22;
import 'dart:ui' as _i25;

import 'package:firebase_auth/firebase_auth.dart' as _i12;
import 'package:flutter/material.dart' as _i24;
import 'package:glaze_manager/models/clay.dart' as _i20;
import 'package:glaze_manager/models/firing_atmosphere.dart' as _i19;
import 'package:glaze_manager/models/firing_profile.dart' as _i18;
import 'package:glaze_manager/models/glaze.dart' as _i16;
import 'package:glaze_manager/models/material.dart' as _i14;
import 'package:glaze_manager/models/test_piece.dart' as _i17;
import 'package:glaze_manager/repositories/clay_repository.dart' as _i5;
import 'package:glaze_manager/repositories/firing_atmosphere_repository.dart'
    as _i7;
import 'package:glaze_manager/repositories/firing_profile_repository.dart'
    as _i6;
import 'package:glaze_manager/repositories/glaze_repository.dart' as _i3;
import 'package:glaze_manager/repositories/material_repository.dart' as _i2;
import 'package:glaze_manager/repositories/tag_repository.dart' as _i8;
import 'package:glaze_manager/repositories/test_piece_repository.dart' as _i4;
import 'package:glaze_manager/repositories/view_history_repository.dart' as _i9;
import 'package:glaze_manager/services/auth_service.dart' as _i10;
import 'package:glaze_manager/services/firestore_service.dart' as _i13;
import 'package:glaze_manager/services/settings_service.dart' as _i23;
import 'package:glaze_manager/services/storage_service.dart' as _i21;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMaterialRepository_0 extends _i1.SmartFake
    implements _i2.MaterialRepository {
  _FakeMaterialRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGlazeRepository_1 extends _i1.SmartFake
    implements _i3.GlazeRepository {
  _FakeGlazeRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTestPieceRepository_2 extends _i1.SmartFake
    implements _i4.TestPieceRepository {
  _FakeTestPieceRepository_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeClayRepository_3 extends _i1.SmartFake
    implements _i5.ClayRepository {
  _FakeClayRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFiringProfileRepository_4 extends _i1.SmartFake
    implements _i6.FiringProfileRepository {
  _FakeFiringProfileRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFiringAtmosphereRepository_5 extends _i1.SmartFake
    implements _i7.FiringAtmosphereRepository {
  _FakeFiringAtmosphereRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTagRepository_6 extends _i1.SmartFake implements _i8.TagRepository {
  _FakeTagRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeViewHistoryRepository_7 extends _i1.SmartFake
    implements _i9.ViewHistoryRepository {
  _FakeViewHistoryRepository_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i11.Stream<_i12.User?> get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _i11.Stream<_i12.User?>.empty(),
          )
          as _i11.Stream<_i12.User?>);

  @override
  _i11.Future<_i12.User?> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i11.Future<_i12.User?>.value(),
          )
          as _i11.Future<_i12.User?>);

  @override
  _i11.Future<_i12.User?> signUpWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmailAndPassword, [email, password]),
            returnValue: _i11.Future<_i12.User?>.value(),
          )
          as _i11.Future<_i12.User?>);

  @override
  _i11.Future<_i12.User?> signInWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassword, [email, password]),
            returnValue: _i11.Future<_i12.User?>.value(),
          )
          as _i11.Future<_i12.User?>);

  @override
  _i11.Future<_i12.UserCredential?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i11.Future<_i12.UserCredential?>.value(),
          )
          as _i11.Future<_i12.UserCredential?>);

  @override
  _i11.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i13.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.MaterialRepository get materials =>
      (super.noSuchMethod(
            Invocation.getter(#materials),
            returnValue: _FakeMaterialRepository_0(
              this,
              Invocation.getter(#materials),
            ),
          )
          as _i2.MaterialRepository);

  @override
  _i3.GlazeRepository get glazes =>
      (super.noSuchMethod(
            Invocation.getter(#glazes),
            returnValue: _FakeGlazeRepository_1(
              this,
              Invocation.getter(#glazes),
            ),
          )
          as _i3.GlazeRepository);

  @override
  _i4.TestPieceRepository get testPieces =>
      (super.noSuchMethod(
            Invocation.getter(#testPieces),
            returnValue: _FakeTestPieceRepository_2(
              this,
              Invocation.getter(#testPieces),
            ),
          )
          as _i4.TestPieceRepository);

  @override
  _i5.ClayRepository get clays =>
      (super.noSuchMethod(
            Invocation.getter(#clays),
            returnValue: _FakeClayRepository_3(this, Invocation.getter(#clays)),
          )
          as _i5.ClayRepository);

  @override
  _i6.FiringProfileRepository get firingProfiles =>
      (super.noSuchMethod(
            Invocation.getter(#firingProfiles),
            returnValue: _FakeFiringProfileRepository_4(
              this,
              Invocation.getter(#firingProfiles),
            ),
          )
          as _i6.FiringProfileRepository);

  @override
  _i7.FiringAtmosphereRepository get firingAtmospheres =>
      (super.noSuchMethod(
            Invocation.getter(#firingAtmospheres),
            returnValue: _FakeFiringAtmosphereRepository_5(
              this,
              Invocation.getter(#firingAtmospheres),
            ),
          )
          as _i7.FiringAtmosphereRepository);

  @override
  _i8.TagRepository get tags =>
      (super.noSuchMethod(
            Invocation.getter(#tags),
            returnValue: _FakeTagRepository_6(this, Invocation.getter(#tags)),
          )
          as _i8.TagRepository);

  @override
  _i9.ViewHistoryRepository get viewHistory =>
      (super.noSuchMethod(
            Invocation.getter(#viewHistory),
            returnValue: _FakeViewHistoryRepository_7(
              this,
              Invocation.getter(#viewHistory),
            ),
          )
          as _i9.ViewHistoryRepository);

  @override
  _i11.Future<void> addMaterial(_i14.Material? material) =>
      (super.noSuchMethod(
            Invocation.method(#addMaterial, [material]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Stream<List<_i14.Material>> getMaterials() =>
      (super.noSuchMethod(
            Invocation.method(#getMaterials, []),
            returnValue: _i11.Stream<List<_i14.Material>>.empty(),
          )
          as _i11.Stream<List<_i14.Material>>);

  @override
  _i11.Future<List<_i14.Material>> getMaterialsOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getMaterialsOnce, []),
            returnValue: _i11.Future<List<_i14.Material>>.value(
              <_i14.Material>[],
            ),
          )
          as _i11.Future<List<_i14.Material>>);

  @override
  _i11.Stream<_i14.Material> getMaterialStream(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getMaterialStream, [id]),
            returnValue: _i11.Stream<_i14.Material>.empty(),
          )
          as _i11.Stream<_i14.Material>);

  @override
  _i11.Future<String?> getMaterialIdByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#getMaterialIdByName, [name]),
            returnValue: _i11.Future<String?>.value(),
          )
          as _i11.Future<String?>);

  @override
  _i11.Future<void> updateMaterial(_i14.Material? material) =>
      (super.noSuchMethod(
            Invocation.method(#updateMaterial, [material]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteMaterial(String? materialId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMaterial, [materialId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> updateMaterialOrder(List<_i14.Material>? list) =>
      (super.noSuchMethod(
            Invocation.method(#updateMaterialOrder, [list]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<List<String>> findOrCreateMaterials(
    List<String>? materialNames,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#findOrCreateMaterials, [materialNames]),
            returnValue: _i11.Future<List<String>>.value(<String>[]),
          )
          as _i11.Future<List<String>>);

  @override
  _i11.Future<String> findOrCreatePigmentID(String? pigmentName) =>
      (super.noSuchMethod(
            Invocation.method(#findOrCreatePigmentID, [pigmentName]),
            returnValue: _i11.Future<String>.value(
              _i15.dummyValue<String>(
                this,
                Invocation.method(#findOrCreatePigmentID, [pigmentName]),
              ),
            ),
          )
          as _i11.Future<String>);

  @override
  _i11.Future<List<String>> findOrCreatePigments(List<String>? pigmentNames) =>
      (super.noSuchMethod(
            Invocation.method(#findOrCreatePigments, [pigmentNames]),
            returnValue: _i11.Future<List<String>>.value(<String>[]),
          )
          as _i11.Future<List<String>>);

  @override
  _i11.Future<void> addGlaze(_i16.Glaze? glaze) =>
      (super.noSuchMethod(
            Invocation.method(#addGlaze, [glaze]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> addGlazesBatch(List<_i16.Glaze>? list) =>
      (super.noSuchMethod(
            Invocation.method(#addGlazesBatch, [list]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Stream<List<_i16.Glaze>> getGlazes() =>
      (super.noSuchMethod(
            Invocation.method(#getGlazes, []),
            returnValue: _i11.Stream<List<_i16.Glaze>>.empty(),
          )
          as _i11.Stream<List<_i16.Glaze>>);

  @override
  _i11.Future<List<_i16.Glaze>> getGlazesOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getGlazesOnce, []),
            returnValue: _i11.Future<List<_i16.Glaze>>.value(<_i16.Glaze>[]),
          )
          as _i11.Future<List<_i16.Glaze>>);

  @override
  _i11.Stream<_i16.Glaze> getGlazeStream(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getGlazeStream, [id]),
            returnValue: _i11.Stream<_i16.Glaze>.empty(),
          )
          as _i11.Stream<_i16.Glaze>);

  @override
  _i11.Future<void> updateGlaze(_i16.Glaze? glaze) =>
      (super.noSuchMethod(
            Invocation.method(#updateGlaze, [glaze]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteGlaze(String? glazeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGlaze, [glazeId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> addTestPiece(_i17.TestPiece? testPiece) =>
      (super.noSuchMethod(
            Invocation.method(#addTestPiece, [testPiece]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  String createTestPieceId() =>
      (super.noSuchMethod(
            Invocation.method(#createTestPieceId, []),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.method(#createTestPieceId, []),
            ),
          )
          as String);

  @override
  _i11.Future<void> setTestPiece(String? id, _i17.TestPiece? testPiece) =>
      (super.noSuchMethod(
            Invocation.method(#setTestPiece, [id, testPiece]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Stream<List<_i17.TestPiece>> getTestPieces() =>
      (super.noSuchMethod(
            Invocation.method(#getTestPieces, []),
            returnValue: _i11.Stream<List<_i17.TestPiece>>.empty(),
          )
          as _i11.Stream<List<_i17.TestPiece>>);

  @override
  _i11.Future<List<_i17.TestPiece>> getTestPiecesOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getTestPiecesOnce, []),
            returnValue: _i11.Future<List<_i17.TestPiece>>.value(
              <_i17.TestPiece>[],
            ),
          )
          as _i11.Future<List<_i17.TestPiece>>);

  @override
  _i11.Stream<List<_i17.TestPiece>> getTestPiecesForGlaze(String? glazeId) =>
      (super.noSuchMethod(
            Invocation.method(#getTestPiecesForGlaze, [glazeId]),
            returnValue: _i11.Stream<List<_i17.TestPiece>>.empty(),
          )
          as _i11.Stream<List<_i17.TestPiece>>);

  @override
  _i11.Stream<_i17.TestPiece> getTestPieceStream(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTestPieceStream, [id]),
            returnValue: _i11.Stream<_i17.TestPiece>.empty(),
          )
          as _i11.Stream<_i17.TestPiece>);

  @override
  _i11.Future<void> updateTestPiece(_i17.TestPiece? testPiece) =>
      (super.noSuchMethod(
            Invocation.method(#updateTestPiece, [testPiece]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteTestPiece(String? testPieceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTestPiece, [testPieceId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> updateViewHistory(String? testPieceId) =>
      (super.noSuchMethod(
            Invocation.method(#updateViewHistory, [testPieceId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Stream<List<String>> getRecentTestPieceIds({int? limit = 20}) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentTestPieceIds, [], {#limit: limit}),
            returnValue: _i11.Stream<List<String>>.empty(),
          )
          as _i11.Stream<List<String>>);

  @override
  _i11.Future<void> addFiringProfile(_i18.FiringProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#addFiringProfile, [profile]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Stream<List<_i18.FiringProfile>> getFiringProfiles() =>
      (super.noSuchMethod(
            Invocation.method(#getFiringProfiles, []),
            returnValue: _i11.Stream<List<_i18.FiringProfile>>.empty(),
          )
          as _i11.Stream<List<_i18.FiringProfile>>);

  @override
  _i11.Future<List<_i18.FiringProfile>> getFiringProfilesOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getFiringProfilesOnce, []),
            returnValue: _i11.Future<List<_i18.FiringProfile>>.value(
              <_i18.FiringProfile>[],
            ),
          )
          as _i11.Future<List<_i18.FiringProfile>>);

  @override
  _i11.Stream<_i18.FiringProfile> getFiringProfileStream(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFiringProfileStream, [id]),
            returnValue: _i11.Stream<_i18.FiringProfile>.empty(),
          )
          as _i11.Stream<_i18.FiringProfile>);

  @override
  _i11.Future<void> updateFiringProfile(_i18.FiringProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateFiringProfile, [profile]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteFiringProfile(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFiringProfile, [profileId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> addFiringAtmosphere(_i19.FiringAtmosphere? atmosphere) =>
      (super.noSuchMethod(
            Invocation.method(#addFiringAtmosphere, [atmosphere]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Stream<List<_i19.FiringAtmosphere>> getFiringAtmospheres() =>
      (super.noSuchMethod(
            Invocation.method(#getFiringAtmospheres, []),
            returnValue: _i11.Stream<List<_i19.FiringAtmosphere>>.empty(),
          )
          as _i11.Stream<List<_i19.FiringAtmosphere>>);

  @override
  _i11.Future<List<_i19.FiringAtmosphere>> getFiringAtmospheresOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getFiringAtmospheresOnce, []),
            returnValue: _i11.Future<List<_i19.FiringAtmosphere>>.value(
              <_i19.FiringAtmosphere>[],
            ),
          )
          as _i11.Future<List<_i19.FiringAtmosphere>>);

  @override
  _i11.Stream<_i19.FiringAtmosphere> getFiringAtmosphereStream(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getFiringAtmosphereStream, [id]),
            returnValue: _i11.Stream<_i19.FiringAtmosphere>.empty(),
          )
          as _i11.Stream<_i19.FiringAtmosphere>);

  @override
  _i11.Future<void> updateFiringAtmosphere(_i19.FiringAtmosphere? atmosphere) =>
      (super.noSuchMethod(
            Invocation.method(#updateFiringAtmosphere, [atmosphere]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteFiringAtmosphere(String? atmosphereId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteFiringAtmosphere, [atmosphereId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> addClay(_i20.Clay? clay) =>
      (super.noSuchMethod(
            Invocation.method(#addClay, [clay]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Stream<List<_i20.Clay>> getClays() =>
      (super.noSuchMethod(
            Invocation.method(#getClays, []),
            returnValue: _i11.Stream<List<_i20.Clay>>.empty(),
          )
          as _i11.Stream<List<_i20.Clay>>);

  @override
  _i11.Future<List<_i20.Clay>> getClaysOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getClaysOnce, []),
            returnValue: _i11.Future<List<_i20.Clay>>.value(<_i20.Clay>[]),
          )
          as _i11.Future<List<_i20.Clay>>);

  @override
  _i11.Stream<_i20.Clay> getClayStream(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getClayStream, [id]),
            returnValue: _i11.Stream<_i20.Clay>.empty(),
          )
          as _i11.Stream<_i20.Clay>);

  @override
  _i11.Future<void> updateClay(_i20.Clay? clay) =>
      (super.noSuchMethod(
            Invocation.method(#updateClay, [clay]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteClay(String? clayId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteClay, [clayId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> updateClayOrder(List<_i20.Clay>? list) =>
      (super.noSuchMethod(
            Invocation.method(#updateClayOrder, [list]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Stream<List<String>> getTags() =>
      (super.noSuchMethod(
            Invocation.method(#getTags, []),
            returnValue: _i11.Stream<List<String>>.empty(),
          )
          as _i11.Stream<List<String>>);

  @override
  _i11.Future<List<String>> getTagsOnce() =>
      (super.noSuchMethod(
            Invocation.method(#getTagsOnce, []),
            returnValue: _i11.Future<List<String>>.value(<String>[]),
          )
          as _i11.Future<List<String>>);

  @override
  _i11.Future<void> addTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#addTag, [tagName]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> addTags(List<String>? tagNames) =>
      (super.noSuchMethod(
            Invocation.method(#addTags, [tagNames]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteTag(String? tagName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTag, [tagName]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i21.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String getUploadPath({required String? testPieceId, required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadPath, [], {
              #testPieceId: testPieceId,
              #name: name,
            }),
            returnValue: _i15.dummyValue<String>(
              this,
              Invocation.method(#getUploadPath, [], {
                #testPieceId: testPieceId,
                #name: name,
              }),
            ),
          )
          as String);

  @override
  _i11.Future<void> uploadTestPieceImage({
    required String? testPieceId,
    required String? name,
    required _i22.Uint8List? bytes,
    String? mimeType,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#uploadTestPieceImage, [], {
              #testPieceId: testPieceId,
              #name: name,
              #bytes: bytes,
              #mimeType: mimeType,
            }),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteTestPieceImage(String? imageUrl) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTestPieceImage, [imageUrl]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> deleteAllTestPieceFiles(String? testPieceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllTestPieceFiles, [testPieceId]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i23.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get gridCrossAxisCount =>
      (super.noSuchMethod(
            Invocation.getter(#gridCrossAxisCount),
            returnValue: 0,
          )
          as int);

  @override
  int get maxGridCrossAxisCount =>
      (super.noSuchMethod(
            Invocation.getter(#maxGridCrossAxisCount),
            returnValue: 0,
          )
          as int);

  @override
  _i24.ThemeMode get themeMode =>
      (super.noSuchMethod(
            Invocation.getter(#themeMode),
            returnValue: _i24.ThemeMode.system,
          )
          as _i24.ThemeMode);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i11.Future<void> setGridCrossAxisCount(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#setGridCrossAxisCount, [count]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  _i11.Future<void> setThemeMode(_i24.ThemeMode? mode) =>
      (super.noSuchMethod(
            Invocation.method(#setThemeMode, [mode]),
            returnValue: _i11.Future<void>.value(),
            returnValueForMissingStub: _i11.Future<void>.value(),
          )
          as _i11.Future<void>);

  @override
  void addListener(_i25.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i25.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
