// Mocks generated by Mockito 5.4.6 from annotations
// in glaze_manager/test/screens/main_tab_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i12;

import 'package:firebase_auth/firebase_auth.dart' as _i4;
import 'package:glaze_manager/models/glaze.dart' as _i7;
import 'package:glaze_manager/models/material.dart' as _i6;
import 'package:glaze_manager/models/test_piece.dart' as _i8;
import 'package:glaze_manager/services/auth_service.dart' as _i2;
import 'package:glaze_manager/services/firestore_service.dart' as _i5;
import 'package:glaze_manager/services/settings_service.dart' as _i11;
import 'package:glaze_manager/services/storage_service.dart' as _i9;
import 'package:image_picker/image_picker.dart' as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.User?> get user =>
      (super.noSuchMethod(
            Invocation.getter(#user),
            returnValue: _i3.Stream<_i4.User?>.empty(),
          )
          as _i3.Stream<_i4.User?>);

  @override
  _i3.Future<_i4.User?> signInAnonymously() =>
      (super.noSuchMethod(
            Invocation.method(#signInAnonymously, []),
            returnValue: _i3.Future<_i4.User?>.value(),
          )
          as _i3.Future<_i4.User?>);

  @override
  _i3.Future<_i4.UserCredential?> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i4.UserCredential?>.value(),
          )
          as _i3.Future<_i4.UserCredential?>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i5.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addMaterial(_i6.Material? material) =>
      (super.noSuchMethod(
            Invocation.method(#addMaterial, [material]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i6.Material>> getMaterials() =>
      (super.noSuchMethod(
            Invocation.method(#getMaterials, []),
            returnValue: _i3.Stream<List<_i6.Material>>.empty(),
          )
          as _i3.Stream<List<_i6.Material>>);

  @override
  _i3.Future<void> updateMaterial(_i6.Material? material) =>
      (super.noSuchMethod(
            Invocation.method(#updateMaterial, [material]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMaterial(String? materialId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMaterial, [materialId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateMaterialOrder(List<_i6.Material>? materials) =>
      (super.noSuchMethod(
            Invocation.method(#updateMaterialOrder, [materials]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addGlaze(_i7.Glaze? glaze) =>
      (super.noSuchMethod(
            Invocation.method(#addGlaze, [glaze]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i7.Glaze>> getGlazes() =>
      (super.noSuchMethod(
            Invocation.method(#getGlazes, []),
            returnValue: _i3.Stream<List<_i7.Glaze>>.empty(),
          )
          as _i3.Stream<List<_i7.Glaze>>);

  @override
  _i3.Future<void> updateGlaze(_i7.Glaze? glaze) =>
      (super.noSuchMethod(
            Invocation.method(#updateGlaze, [glaze]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteGlaze(String? glazeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteGlaze, [glazeId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addTestPiece(_i8.TestPiece? testPiece) =>
      (super.noSuchMethod(
            Invocation.method(#addTestPiece, [testPiece]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i8.TestPiece>> getTestPieces() =>
      (super.noSuchMethod(
            Invocation.method(#getTestPieces, []),
            returnValue: _i3.Stream<List<_i8.TestPiece>>.empty(),
          )
          as _i3.Stream<List<_i8.TestPiece>>);

  @override
  _i3.Future<void> updateTestPiece(_i8.TestPiece? testPiece) =>
      (super.noSuchMethod(
            Invocation.method(#updateTestPiece, [testPiece]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTestPiece(String? testPieceId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTestPiece, [testPieceId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i9.StorageService {
  MockStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String?> uploadTestPieceImage(_i10.XFile? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#uploadTestPieceImage, [imageFile]),
            returnValue: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);
}

/// A class which mocks [SettingsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSettingsService extends _i1.Mock implements _i11.SettingsService {
  MockSettingsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get gridCrossAxisCount =>
      (super.noSuchMethod(
            Invocation.getter(#gridCrossAxisCount),
            returnValue: 0,
          )
          as int);

  @override
  int get maxGridCrossAxisCount =>
      (super.noSuchMethod(
            Invocation.getter(#maxGridCrossAxisCount),
            returnValue: 0,
          )
          as int);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> setGridCrossAxisCount(int? count) =>
      (super.noSuchMethod(
            Invocation.method(#setGridCrossAxisCount, [count]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void addListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i12.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
